---
# tasks file for ssh-devops

## Install sudo package ##
- name: Install sudo
  apt:
    name: sudo
    state: present
  when: ansible_os_family == "Debian"

- name: Install EPEL release
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "CentOS"

- name: Install sudo
  yum:
    name: sudo
    state: present
  when: ansible_os_family == "CentOS" 

## Create required group for user management ##
# Create Group 'devops'
- name: Ensure group "devops" exists
  group:
    name: devops
    state: present

# Create group 'developer'
- name: Ensure group "developer" exists
  group:
    name: developer
    state: present

# Create deploy user. Present by default on all systems
- name: Add users to devops group 
  user:
    name: deploy
    state: present
    shell: /bin/bash
    group: devops
    comment: deploy user for Devops 
    createhome: yes

- name: Add users to developer group 
  user:
    name: developer
    state: present
    shell: /bin/bash
    group: developer
    comment: developer user for Devs 
    createhome: yes

## Sudoers config ##
# - name: Copy sudoers file for safety
#   command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: Copy sudoers file for safety
  become: yes
  copy: 
    src: /etc/sudoers
    dest: /etc/sudoers.tmp
    remote_src: true
    backup: yes 
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/visudo -cf %s

- name: Create sudoers file backup
  become: yes
  copy: 
    src: /etc/sudoers
    dest: /etc/sudoers.bak
    remote_src: true
    backup: yes 
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/visudo -cf %s

- name: configure sudoers for Devops
  lineinfile:   dest=/etc/sudoers.d/ansible
                line="%devops ALL=(ALL) ALL"
                state=present
                create=yes
                validate='/usr/sbin/visudo -cf %s'

# - name: configure sudoers
#   lineinfile:   dest=/etc/sudoers.d/ansible
#                 line="%developer ALL=(ALL) ALL"
#                 state=present
#                 create=yes
#                 validate='/usr/sbin/visudo -cf %s'

- name: Add configured user accounts to passwordless sudoers.
  lineinfile:
    dest: /etc/sudoers
    line: 'deploy ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: '/usr/sbin/visudo -cf %s'

